RUN apt-get update && apt-get -y install git mercurial meld
RUN apt-get -y install vim tmux wget
RUN apt-get -y install docker.io

RUN apt-get -y install npm

ENV HOME /home
WORKDIR /home

VOLUME ["/home"]

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["bash"]
